# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://cega.github.io',
                'git_url': 'https://github.com/cega/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')},
            'nbdev_hello_world.modulo': { 'nbdev_hello_world.modulo.foo': ('core.html#foo', 'nbdev_hello_world/modulo.py'),
                                          'nbdev_hello_world.modulo.say_hello': ('core.html#say_hello', 'nbdev_hello_world/modulo.py')}}}